version: '3.8'

services:
  database:
    image: postgres:16
    container_name: postgres-web-db
    environment:
      - POSTGRES_USER=edilson_db
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=edilson_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pgdata: